import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="flex justify-center h-dvh" translate="no" lang="en">
      <body className="max-w-screen-xl flex-col flex w-full">
        <Header />
        <main className="flex-1"> {children} </main>
      </body>
    </html>
  );
}